elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
logstash:
  image: jaydp17/elk-logstash
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
